name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven

      # 3. Configure Maven settings
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers>
            <server><id>github-commons</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server>
            <server><id>github-seguridad</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server>
          </servers></settings>" > ~/.m2/settings.xml

      # 4. Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 5. Compile project
      - name: Compile project
        run: mvn clean package

      # 6. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build Docker image
      - name: Build Docker image
        run: docker build -t mariafernanda2798/reservas:latest .

      # 8. Push Docker image
      - name: Push Docker image
        run: docker push mariafernanda2798/reservas:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2. Deploy to Azure Web App for Containers
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: "sistema-sah-reservas-ms"
          images: "mariafernanda2798/reservas:latest"
